/**
 * Calendars Common Javascript
 */
var CalendarsCommon = {
  DISP_TYPE_SMALL_MONTHLY: 1,
  DISP_TYPE_LARGE_MONTHLY: 2,
  DISP_TYPE_WEEKLY: 3,
  DISP_TYPE_DAILY: 4,
  DISP_TYPE_TSCHEDULE: 5,
  DISP_TYPE_MSCHEDULE: 6
};

